SpaceInvadersNoFrameskip-v4:
  env_wrapper:
    - stable_baselines3.common.atari_wrappers.AtariWrapper
  frame_stack: 3
  policy: 'CnnPolicy'
  n_timesteps: !!float 1e6
  buffer_size: 100000
  learning_rate: !!float 4.964132854171392e-05
  batch_size: 64
  learning_starts: 110000
  target_update_interval: 4000
  train_freq: 2
  gradient_steps: 5
  exploration_fraction: 0.3178717485441687
  exploration_final_eps: 0.09178937437643139
  # If True, you need to deactivate handle_timeout_termination
  # in the replay_buffer_kwargs
  optimize_memory_usage: False